### ISSUE TITLE
Widgets are not enabled in Jupyter Lab.

### ISSUE THREAD

**Issue by fabclmnt** [ydataai/docker-github-runner#1]
Jupyter Lab's widgets are not enabled. This is important to run exploratory data analysis. 

1. Include widgets as a lib to have installed in all the available bundles. 

2. Enable widgets for Jupyter Lab https://ipywidgets.readthedocs.io/en/latest/user_install.html#installing-the-jupyterlab-extension

**Comment by rafaelcpalmeida** [comment]
Fixed per https://github.com/ydataai/dockerfiles/pull/38
